eval "$(starship init zsh)"
eval "$(zoxide init zsh)"

source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh

[ -s /etc/profile.d/autojump.zsh ] && source /etc/profile.d/autojump.zsh

alias ls='exa -T -L 1'
alias l='ls'
alias ll='exa -hal'
alias lt='exa -T'

alias rm='trash-put'

alias sudo='sudo -A'

alias reload='source ~/.zshrc'

eval $(dircolors)

zstyle ':completion:*' menu select
zstyle -e ':completion:*:default' list-colors 'reply=("${PREFIX:+=(#bi)($PREFIX:t)(?)*==34=34}:${(s.:.)LS_COLORS}")';

zstyle ':completion:*' matcher-list '' 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=*' 'l:|=* r:|=*'

# Declare the variable
typeset -A ZSH_HIGHLIGHT_STYLES

ZSH_HIGHLIGHT_STYLES[command]='fg=blue'
	ZSH_HIGHLIGHT_STYLES[reserved-word]='fg=blue'
	ZSH_HIGHLIGHT_STYLES[alias]='fg=blue'
		ZSH_HIGHLIGHT_STYLES[suffix-alias]='fg=blue'
		ZSH_HIGHLIGHT_STYLES[global-alias]='fg=blue'
	ZSH_HIGHLIGHT_STYLES[builtin]='fg=blue'
	ZSH_HIGHLIGHT_STYLES[function]='fg=blue'
	ZSH_HIGHLIGHT_STYLES[precommand]='fg=blue'

ZSH_HIGHLIGHT_STYLES[path]='fg=cyan,underline'
	ZSH_HIGHLIGHT_STYLES[single-hyphen-option]='fg=cyan'
	ZSH_HIGHLIGHT_STYLES[single-hyphen-option]='fg=cyan'
	ZSH_HIGHLIGHT_STYLES[globbing]='fg=cyan'

	ZSH_HIGHLIGHT_STYLES[single-quoted-argument]='fg=yellow'
		ZSH_HIGHLIGHT_STYLES[single-quoted-argument-unclosed]='fg=yellow'
	ZSH_HIGHLIGHT_STYLES[double-quoted-argument]='fg=yellow'
		ZSH_HIGHLIGHT_STYLES[double-quoted-argument-unclosed]='fg=yellow'

ZSH_HIGHLIGHT_STYLES[back-double-quoted-argument]='fg=white'

ZSH_HIGHLIGHT_STYLES[default]='fg=cyan'

# Lines configured by zsh-newuser-install
HISTFILE=~/.zsh_history
HISTSIZE=1000
SAVEHIST=3000
bindkey -v
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/home/absolpega/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall
